// Generated by Wrangler by running `wrangler types`

interface Env {
	POSTHOG_API_KEY: "phc_oYFcMPG9V4ARE4INIzfQQnLmADFN2GRLaYfDFiLSaQ6";
	POSTHOG_API_HOST: "https://us.i.posthog.com";
	JOIN_TOKEN_SECRET: string;
	rooms: DurableObjectNamespace<import("./src/server").Room>;
}
