export const INTENT_TYPES = [
  "card.add",
  "card.add.batch",
  "card.counter.adjust",
  "card.duplicate",
  "card.move",
  "card.remove",
  "card.reveal.set",
  "card.tap",
  "card.transform",
  "card.untapAll",
  "card.update",
  "coin.flip",
  "counter.global.add",
  "deck.load",
  "deck.mulligan",
  "deck.reset",
  "deck.unload",
  "dice.roll",
  "library.discard",
  "library.draw",
  "library.shuffle",
  "library.view",
  "library.view.close",
  "library.view.ping",
  "player.join",
  "player.leave",
  "player.update",
  "room.lock",
  "ui.battlefieldScale.set",
  "zone.add",
  "zone.reorder",
] as const;

export type IntentType = (typeof INTENT_TYPES)[number];
